import "./globals.css"
import type { Metadata } from "next"
// import { Inter } from "next/font/google";
import NavBar from "./NavBar"
import "@radix-ui/themes/styles.css"
import { Container, Theme, ThemePanel } from "@radix-ui/themes"
import AuthProvider from "./auth/Provider"
import QueryClientProvider from "./QueryClientProvider"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"
import CursorManager from "./CursorManager"

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {" "}
        {/* className={inter.className} */}
        <QueryClientProvider>
          <AuthProvider>
            <Theme appearance="light" accentColor="sky" radius="small">
              <NavBar />
              <CursorManager />
              <main className="p-3 bg-teal-50 pt-16">
                <Container>{children}</Container>
              </main>
            </Theme>
            <ReactQueryDevtools />
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
